# Generated by Django 2.2.3 on 2019-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mypage', '0003_auto_20190719_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ordered_product_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'user_order',
                'managed': False,
            },
        ),
    ]
