# Generated by Django 2.2.1 on 2019-08-09 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=45)),
                ('pub_date', models.DateTimeField(default='2019-08-10 12:00', verbose_name='date published')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QABoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.CharField(max_length=45)),
                ('pub_date', models.DateTimeField(default='2019-08-10 12:00', verbose_name='date published')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QABoardComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=45)),
                ('q_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.QABoard')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
