# Generated by Django 2.2.3 on 2019-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pay', '0003_auto_20190719_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg', models.CharField(max_length=45)),
                ('pay_method', models.CharField(max_length=45)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=45, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=45, null=True)),
                ('buyer_tel', models.CharField(blank=True, max_length=45, null=True)),
                ('buyer_addr', models.CharField(blank=True, max_length=45, null=True)),
                ('buyer_postcode', models.CharField(blank=True, max_length=45, null=True)),
                ('m_redirect_url', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'pay',
                'managed': False,
            },
        ),
    ]
