# Generated by Django 2.2.3 on 2019-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_product_productcolor_productlength_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_value', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'property_name',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductLength',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
