# Generated by Django 2.2.1 on 2019-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('address', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('tel', models.CharField(max_length=45)),
                ('monthly_amount', models.CharField(blank=True, default='NULL', max_length=45)),
                ('donate_value', models.IntegerField(blank=True, default=0)),
                ('coin', models.IntegerField(blank=True, default=0)),
                ('post_code', models.CharField(blank=True, default='NULL', max_length=45)),
                ('term', models.IntegerField(blank=True, default=1)),
                ('use_period', models.IntegerField(blank=True, default=0)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'ordering': ('email',),
                'managed': True,
            },
        ),
    ]
